title:              My Blog
email:              fbelinchon@gmail.com
description:        Este es mi blog
author:             Francisco Belinch√≥n
baseurl:            "/blogs"
url:                "https://fbelinchon.github.io"

# Social Profiles
twitter_username:   fbelinchon
github_username:    fbelinchon
facebook_username:  StartBootstrap
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
lang: es
use_math: true

markdown:           kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  
paginate:           5
paginate_path:      "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

